### ISSUE TITLE
add the urdf(xacro format) for Robotis OP2 in RViz

### ISSUE THREAD

**Issue by robotpilot** [ROBOTIS-OP/robotis_op_common#1]
add the urdf(xacro format) for Robotis OP2 in RViz
- add the robotis_op2.xacro for robot description
- add the materials.xacro for color of RViz
- add the launch file for running in RViz

**Comment by robotpilot** [comment]
![robotis_op2_in_rviz](https://cloud.githubusercontent.com/assets/2698667/9159798/833bad26-3f6a-11e5-9f2c-dcfce5a855c9.png)

It is captured picture when running the robotis_op_description in RViz.

**Comment by robotpilot** [comment]
You can test this package using below command.

``` sh
roslaunch robotis_op_description robotis_op2_rviz.launch 
```

**Comment by robotpilot** [comment]
I want to get the real STL files of gripper, like  MP_ARM_GRIPPER_FIX_R.
MP_ARM_GRIPPER_xxx series is not STL, it is just box type.

**Comment by kdaun** [comment]
I asked for the real mesh files, but didn't receive them yet. 
Anyways, I extended the usage of the xacro scripts to build a more modular model https://github.com/ROBOTIS-OP/robotis_op_common/commit/679713ba5a395e467a1752d228003df69b4beed4
